stages:
  - continuose-intgeration
  - build-image
  - prpvide-infrastructure
  - acceptance-test

build-backend-image:
   stage: build-image
   image: docker:dind
   services:
    - docker:dind
   script:
    - cd backend
    - docker build -t steinko/msw-backend
    - docker push steinko/msw-backend .
    - cd ..

provide-infrastructure-test:
   image: pulumi/pulumi-nodejs
   stage: prpvide-infrastructure
   script:
    - cd deploy
    - npm install
    - export PULUMI_ACCESS_TOKEN="$PULUMI_ACCESS_TOKEN"
    - pulumi login
    - pulumi stack select dev
    - pulumi up -y
    - BACKEND_URL=http://$(pulumi stack output backendUrl)/helloworld >> test.env
    - cd ..

