stages:
  - continuose-intgeration
  - acceptance-test
  

integration-test:
  stage: continuose-intgeration
  image: node  
  script:
    - npm install
    - npm run test -- --coverage --watchAll=false
    - npm run eslint

test:
  image: node:latest
  stage: acceptance-test
  script:
    # install dependencies
    - npm ci
    # start the server in the background
    - npm run start:ci &
    # run Cypress tests
    - npm run cypress:run