stages:
  - continuose-intgeration
  - acceptance-test
  

integration-test:
  stage: continuose-intgeration
  image: node  
  script:
    - npm install
    - npm run test -- --coverage --watchAll=false
    - npm run eslint

test:
  image: cypress/base:10
  stage: acceptance-test
  script:
    - npm i
    - npm start
    - npm run cypress:run