stages:
  - continuose-intgeration
  - acceptance-test
  

integration-test:
  stage: continuose-intgeration
  image: node  
  script:
    - npm install
    - npm run test -- --coverage --watchAll=false
    - npm run eslint

acceptance-test:
  stage: acceptance-test
  image: node  
  script:
    - npm install
    - npm run cypress:run